### ISSUE TITLE
Configuration check error.

### ISSUE THREAD

**Issue by acordill** [thomasloven/lovelace-browser-commander#1]
Just did a check config on my hassio instance 0.88.1 and got the following error.
Package browser_commander setup failed. Component script cannot be merged. Expected a dict.
I have no clue what it might be.

**Comment by thomasloven** [comment]
Me neither. Seems like something went terribly wrong, like you tried to add it to configuration.yaml instead of ui-lovelace.yaml or the raw editor or something...
Try removing all automations and scripts calling browser_commande and see if you can find it.

**Comment by thomasloven** [comment]
Any luck?
