### ISSUE TITLE
Doesn't work if User not in Admin Group

### ISSUE THREAD

**Issue by VDRainer** [thomasloven/lovelace-browser-commander#3]
Sorry Thomas, maybe not YOUR issue, but thought i post it here.

Browser commander does nothing (using debug, navigate and lovelace-reload) if the logged in user is not in the admin group.

There was a similar [issue](https://github.com/home-assistant/home-assistant-polymer/issues/2954) with UI state refresh, maybe it's related.

Thank you in advance.

**Comment by thomasloven** [comment]
Thank you.
It seems a non admin user cannot subscribe to the `browser_command` event....

I may need to come up with some other way to communicate with the plugin...

**Comment by VDRainer** [comment]
From the user settings:

> The users group is a work in progress. The user will be unable to administer the instance via the UI. We're still auditing all management API endpoints to ensure that they correctly limit access to administrators. 

Maybe it 'heals' itself with the passage of time. :smile:
