### ISSUE TITLE
Custom Updater support?

### ISSUE THREAD

**Issue by rdehuyss** [thomasloven/lovelace-browser-commander#4]
Hi Thomas,

I would like to use this plugin and wondered if it's possible to support the custom_updater for this plugin.

Cheers,
Ronald

**Comment by louis-lau** [comment]
Seeing as custom_updater is being deprecated it may be preferable to add support for [HACS](https://github.com/custom-components/hacs).

It can already be added using HACS but because there are no releases on github it will not know when it should be updated.

**Comment by ludeeus** [comment]
That is my bad...
Next version will also support commits, as a metric for version control of elements that do not use releases.

Aslo, AFAIK this has had support for custom_updater since it's first commit :)
